config/routes.rb
RottenMangoes::Application.routes.draw do

  resources :movies do
      resources :reviews, only: [:new, :create]
    end
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  
  namespace :admin do
    resources :users 
  end

  root to: 'movies#index'

  

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :reviews
  
  mount_uploader :image, ImageUploader

   validates :title,
        presence: true

      validates :director,
        presence: true

      validates :runtime_in_minutes,
        numericality: { only_integer: true }

      validates :description,
        presence: true

      validates :release_date,
        presence: true

      validate :release_date_is_in_the_future

      def review_average
        if reviews.size == 0
          return 1
        else
        reviews.sum(:rating_out_of_ten)/reviews.size
       end
      end



      def self.search(query)
        # where(:title, query) -> This would return an exact match of the query
        where("title like ?", "%#{query}%") 
      end


      protected

      def release_date_is_in_the_future
        if release_date.present?
          errors.add(:release_date, "should probably be in the future") if release_date < Date.today
        end
      end

end

app/models/review.rb
class Review < ActiveRecord::Base
 belongs_to :user
      belongs_to :movie

      validates :user,
        presence: true

      validates :movie,
        presence: true

      validates :text,
        presence: true

      validates :rating_out_of_ten,
        numericality: { only_integer: true }
      validates :rating_out_of_ten,
        numericality: { greater_than_or_equal_to: 1 }
      validates :rating_out_of_ten,
        numericality: { less_than_or_equal_to: 10 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews
  has_secure_password

  def full_name
    "#{firstname} #{lastname}"
  end
  def is_admin?
    current_user.admin == true
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  def index
   @user = User.all.page(params[:page]).per(5)
  end

  def create
   @user = User.new(user_params)

      if @user.save
        redirect_to admin_user_path, notice: "#{@user.firstname} was submitted successfully!"
      else
        render :new
      end
  end

  def new
    @user = User.new
  end

  def edit
    @silly = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to admin_user_path(@user)
    else
      render :edit
    end

  end

  def show
     @user = User.find(params[:id])

  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
     UserMailer.withdraw_user_email(@user).deliver
    redirect_to admin_users_path
  end

  def user_params
    params.require(:user).permit(
      :email, :password, :password_confirmation, :firstname, :lastname, :admin
    )
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def is_admin?
    current_user.admin == "true"
  end


  helper_method :current_user, :is_admin?
      
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
   if params[:search]
    
    @movies = Movie.search(params[:search]).order("created_at DESC")
    else
      @movies = Movie.all
    end
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def edit
    @movie = Movie.find(params[:id])
  end

   def create
    @movie = Movie.new(movie_params)

    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end

  def update
    @movie = Movie.find(params[:id])

    if @movie.update_attributes(movie_params)
      redirect_to movie_path(@movie)
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end


  protected

  def movie_params
    params.require(:movie).permit(
      :title, :release_date, :director, :runtime_in_minutes, :description,:image, :remote_image_url
    )
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :restrict_access
  before_filter :load_movie
  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully"
    else
      render :new
    end
  end

  protected
  def load_movie
    @movie = Movie.find(params[:movie_id])
  end
  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "Welcome back, #{user.firstname}!"
    else
      flash.now[:alert] = "Log in failed..."
      render :new
    end

  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Adios!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
   @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to movies_path, notice: "Welcome aboard, #{@user.firstname}!" if @user.admin = "false"
    else
      render :new
    end
  end

protected

  def user_params
    params.require(:user).permit(:email, :admin, :firstname, :lastname, :password, :password_confirmation)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

   def formatted_date(date)
        date.strftime("%b %d, %Y")
      end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb

    <%= form_for [:admin, @silly] do |f| %>
      <% if @silly.errors.any? %>
        <div>
          <%= pluralize(@silly.errors.count, "error") %> prevented the account from being created:
          <ul>
            <% @silly.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div>
        <%= f.label "email" %><br>
        <%= f.text_field "email" %>
      </div>
      <div>
        <%= f.label "firstname", "First Name" %><br>
        <%= f.text_field "firstname" %>
      </div>
      <div>
        <%= f.label "lastname", "Last Name" %><br>
        <%= f.text_field "lastname" %>
      </div>
      <div>
        <%= f.label "password" %><br>
        <%= f.password_field "password" %>
      </div>
      <div>
        <%= f.label "password_confirmation" %><br>
        <%= f.password_field "password_confirmation" %>
      </div>
      <div>
        <%= f.radio_button(:admin, "true") %>
        <%= f.label(:admin_admin, "Admin") %>
        <%= f.radio_button(:admin, "false") %>
        <%= f.label(:admin_general, "General") %>
      </div>
      <div><%= f.submit "Submit" %></div>
    <% end %>

app/views/admin/users/edit.html.erb
<%= render 'form' %>

app/views/admin/users/index.html.erb

  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title">Users</h3>
          </div>
          <table class="table table-hover" id="dev-table">
            <thead>
              <tr>
                <th>#</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>User type</th>
              </tr>
            </thead>
             <%= paginate @user %><br/>

  
            <tbody>
            <% @user.each do |u| %>
              <tr>
                <td><%= u.id %> </td>
                <td><%= u.firstname %> </td>
                <td><%= u.lastname %> </td>
              
                 <% if u.admin == "true" %>
                <td><%= link_to "Admin", admin_user_path(u) %></td>
                 <% else %>
                 <td><%= link_to "General", admin_user_path(u) %></td>
                 <% end %>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>


app/views/admin/users/new.html.erb
<%= render 'form' %>

app/views/admin/users/show.html.erb

<h4>First name:<%= @user.firstname %> (<%= link_to "edit", edit_admin_user_path(@user) %>, <%= link_to "delete", admin_user_path(@user), method: :delete, confirm: "You sure?" %>)<br/>
Last name: <%= @user.lastname %> <br/>
Email:<%= @user.email %> <br/>
Created on : <%= formatted_date(@user.created_at) %><br/>
Updated on : <%= formatted_date(@user.updated_at) %><br/>
<% if @user.admin == "true" %>
Profile type: Admin
<% else %>
Profile type: General
<% end %>

<hr>

app/views/layouts/_footer.html.erb


<footer>
  <small>
 

    <% if current_user %>
    Signed in as <%= current_user.full_name %> (<%= link_to "Log out", session_path("current"), method: :delete %>
    
    <% if current_user.admin  == "true" %>)
    <%= link_to "Users", admin_users_path %>
    <% end %>
    <% else %>
    <%= link_to "Log In", new_session_path %> | <%= link_to "Sign Up", new_user_path %>
    <% end %>
  </small>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  
   

  <title>RottenMangoes</title>

  
  <!-- Custom CSS -->
  <style>
    body {
      padding-top: 70px;
      /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
    }
  </style>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
        <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
        <%= csrf_meta_tags %>
      </head>

      <body>

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
          <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">Disney Delicacy</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                <li>
                  <a href='/movies#index'>Home</a>
                </li>
                <li>
                  <a href="#">Reviews</a>
                </li>
                <li>
                  <a href="users/new">Login</a>
                </li>
              </ul>
            
  <%= form_tag(movies_path, :method => "get", class: "navbar-form", id: "search-form") do %>
    <div class="input-append">
      <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search Movies" %>
      <!-- In order to have the "search" icon int the button, we need to use plain HTML instead 
           of using a Rails form helper -->
      <button class="btn" type="submit"><i class="icon-search"></i></button>
    </div>
  <% end %>
            </div>
            <!-- /.navbar-collapse -->
          </div>
          <!-- /.container -->
        </nav>

        <!-- Page Content -->
        <div class="container">

          <% flash.each do |key, value| %>
          <%= content_tag(:div, value) %>
          <% end %>
                  <%= yield %>
          <%= render 'layouts/footer' %>
        </div>
        <!-- /.container -->

        
      </body>

      </html>

app/views/movies/_form.html.erb
 <%= form_for @movie, :html => {:multipart => true } do |f| %>
     
      <% if @movie.errors.any? %>
        <div>
          <%= pluralize(@movie.errors.count, "error") %> prevented this movie from being submitted:
          <ul>
            <% @movie.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>


  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <form class="form-horizontal" role="form">
        <fieldset>

          <!-- Form Name -->
          <legend>Address Details</legend>

          <!-- Text input-->
          <div class="form-group">
            <label class="col-sm-2 control-label" for="textinput">Line 1</label>
            <div class="col-sm-10">
              <input type="text" placeholder="Address Line 1" class="form-control">
            </div>
          </div>

          <!-- Text input-->
          <div class="form-group">
            <label class="col-sm-2 control-label" for="textinput">Line 2</label>
            <div class="col-sm-10">
              <input type="text" placeholder="Address Line 2" class="form-control">
            </div>
          </div>

          <!-- Text input-->
          <div class="form-group">
            <label class="col-sm-2 control-label" for="textinput">City</label>
            <div class="col-sm-10">
              <input type="text" placeholder="City" class="form-control">
            </div>
          </div>

          <!-- Text input-->
          <div class="form-group">
            <label class="col-sm-2 control-label" for="textinput">State</label>
            <div class="col-sm-4">
              <input type="text" placeholder="State" class="form-control">
            </div>

            <label class="col-sm-2 control-label" for="textinput">Postcode</label>
            <div class="col-sm-4">
              <input type="text" placeholder="Post Code" class="form-control">
            </div>
          </div>



          <!-- Text input-->
          <div class="form-group">
            <label class="col-sm-2 control-label" for="textinput">Country</label>
            <div class="col-sm-10">
              <input type="text" placeholder="Country" class="form-control">
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
              <div class="pull-right">
                <button type="submit" class="btn btn-default">Cancel</button>
                <button type="submit" class="btn btn-primary">Save</button>
              </div>
            </div>
          </div>

        </fieldset>
      </form>
    </div><!-- /.col-lg-12 -->
</div><!-- /.row -->

      <div>
        <%= f.label "title" %><br>
        <%= f.text_field "title" %>
      </div>
      <div>
        <%= f.label "release_date" %><br>
        <%= f.date_field "release_date" %>
      </div>
      <div>
        <%= f.label "director" %><br>
        <%= f.text_field "director" %>
      </div>
      <div>
        <%= f.label "runtime_in_minutes" %><br>
        <%= f.number_field "runtime_in_minutes" %>
      </div>
      
     
      <div>
        <%= f.label "image" %><br>
        <%= f.file_field "image" %> or upload by remote url
        <%= f.label "remote_image_url" %> <br>
        <%= f.text_field "remote_image_url" %>
      </div>

      <div>
        <%= f.label "description" %><br>
        <%= f.text_area "description" %>
      </div>
      <div>
        <%= f.submit "Submit" %> 
      </div>
    <% end %>

app/views/movies/index.html.erb
  <div class="container">
   <h1>Whats the best of the LOT!!</h1>
    <%= link_to "Submit a movie!", new_movie_path %>

  <div class="row">
    <div class="span12">
          <div class="well"> 
                <div id="myCarousel" class="carousel slide">
                 
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                </ol>
                 
                <!-- Carousel items -->
               
                <div class="carousel-inner">
                <div class= "item active">
                <div class="row-fluid">
                <% @movies.each_with_index do |movie,i| %> 
                                    
                      <div class="col-sm-3"><a href="<%= movie_path(movie)%>" class="thumbnail"><%=image_tag(movie.image.url(:thumb))%> </a>

                      </div>
                    <%  if (i+1)%3 == 0 then  %>  
                      </div><!--/row-fluid-->
                      </div><!--/item-->
                      <div class= "item">
                       <div class="row-fluid">
                    <% end %>

                           

                <% end %>
                </div>
                </div>

                
                  
                </div><!--/carousel-inner-->
                 
                <a class="left carousel-control" href="#myCarousel" data-slide="prev">‹</a>
                <a class="right carousel-control" href="#myCarousel" data-slide="next">›</a>
                </div><!--/myCarousel-->
                 
            </div><!--/well-->   
    </div>
  </div>
</div>

app/views/movies/index_junk_prev_data.erb
<h1>Rotten Mangoes</h1>
    <%= link_to "Submit a movie!", new_movie_path %>
    <hr>
    <% @movies.each do |movie| %>
      <%= link_to image_tag(movie.image.url(:thumb)), movie_path(movie) %>
      <h2><%= link_to movie.title, movie_path(movie) %></h2>
      <h3><%= movie.release_date %></h3>
      <h4>Dir. <%= movie.director %> | <%= movie.runtime_in_minutes %> minutes</h4>
      <p><%= movie.description %></p>
      <hr>
    <% end %>

app/views/movies/show.html.erb
<<<<<<< HEAD
 <%= link_to "Back to all movies", movies_path %><br/>

 <%=image_tag @movie.image.url(:thumb) if @movie.image? %>
 
 <h2><%= @movie.title %> (<%= link_to "edit", edit_movie_path(@movie) %>, <%= link_to "delete", movie_path(@movie), method: :delete, confirm: "You sure?" %>)</h2>
 
 <h3><%= formatted_date(@movie.release_date) %></h3>
 <h4>Dir. <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes</h4>
 <p><%= @movie.description %></p>
 <hr>

 <h3>Reviews of <em><%= @movie.title %> Average Rating <%= @movie.review_average %></em></h3>
 <% if current_user %>
 <% @movie.reviews.each do |review| %>
 <p><%= review.text %></p>
 <p><%= review.rating_out_of_ten %>/10</p>
 <small>- <%= review.user.full_name %></small><br/>
 <% end %>
 <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
 <% else %>
 <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p> 
=======
 <%= link_to "Back to all movies", movies_path %><br/>

 <%=image_tag @movie.image.url(:thumb) if @movie.image? %>
 
 <h2><%= @movie.title %> (<%= link_to "edit", edit_movie_path(@movie) %>, <%= link_to "delete", movie_path(@movie), method: :delete, confirm: "You sure?" %>)</h2>

 <h3><%= formatted_date(@movie.release_date) %></h3>
 <h4>Dir. <%= @movie.director %> | <%= @movie.runtime_in_minutes %> minutes</h4>
 <p><%= @movie.description %></p>
 <hr>

 <h3>Reviews of <em><%= @movie.title %> Average Rating <%= @movie.review_average %></em></h3>
 <% if current_user %>
 <% @movie.reviews.each do |review| %>
 <p><%= review.text %></p>
 <p><%= review.rating_out_of_ten %>/10</p>
 <small>- <%= review.user.full_name %></small><br/>
 <% end %>
 <p><%= link_to "Write a review!", new_movie_review_path(@movie) %></p>
 <% else %>
 <p>Please <%= link_to "log in", new_session_path %> to see reviews and add your own.</p> 
>>>>>>> feature/admins
 <% end %>

app/views/reviews/new.html.erb
<%= link_to "Back to movie", movie_path(@movie) %><br/>

    <h2>Write a review of <em><%= @movie.title %></em>.</h2>

    <%= form_for([@movie, @review]) do |f| %>
      <% if @review.errors.any? %>
        <div>
          <%= pluralize(@review.errors.count, "error") %> prevented the review from being saved:
          <ul>
            <% @review.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div>
        <%= f.label "text" %><br>
        <%= f.text_area "text" %>
      </div>
      <div>
        <%= f.label "rating_out_of_ten" %><br>
        <%= f.number_field "rating_out_of_ten" %>
      </div>
      <div><%= f.submit "Submit" %></div>
    <% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<!-- 

<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-4 well well-sm">
     Sign up!
      <form action="#" method="post" class="form" role="form">
       <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div>
          <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
        <div class="row">
          <div class="col-xs-6 col-md-6">
            <input class="form-control" name="firstname" placeholder="First Name" type="text"
            required autofocus />
          </div>
          <div class="col-xs-6 col-md-6">
            <input class="form-control" name="lastname" placeholder="Last Name" type="text" required />
          </div>
        </div>
        <input class="form-control" name="email" placeholder="Your Email" type="email" />
       
       
        <input class="form-control" name="password" placeholder="New Password" type="password" />

         <input class="form-control" name="password_confirmation" placeholder="Re-enter Password" type="password" />
        
          <label class="radio-inline">
            <input type="radio" name="admin" id="inlineCheckbox1" value="admin" />
            Admin
          </label>
          <label class="radio-inline">
            <input type="radio" name="user" id="inlineCheckbox2" value="user" />
            User
          </label>
          <br />
          <br />
          <button class="btn btn-lg btn-primary btn-block" type="submit">
            Sign up</button>
             <% end %>
         
        </div>
      </div>
    </div> -->
    <!-- --------------------------------------------------------------------------- -->


<h1>Sign Up</h1>
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div>
          <%= pluralize(@user.errors.count, "error") %> prevented the account from being created:
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div>
        <%= f.label "email" %><br>
        <%= f.text_field "email" %>
      </div>
      <div>
        <%= f.label "firstname", "First Name" %><br>
        <%= f.text_field "firstname" %>
      </div>
      <div>
        <%= f.label "lastname", "Last Name" %><br>
        <%= f.text_field "lastname" %>
      </div>
      <div>
        <%= f.label "password" %><br>
        <%= f.password_field "password" %>
      </div>
      <div>
        <%= f.label "password_confirmation" %><br>
        <%= f.password_field "password_confirmation" %>
      </div>
      <div>
        <%= f.radio_button(:admin, "true") %>
        <%= f.label(:admin_admin, "Admin") %>
        <%= f.radio_button(:admin, "false") %>
        <%= f.label(:admin_general, "General") %>
      </div>
      <div><%= f.submit "Submit" %></div>
    <% end %>